# Generated by Django 4.2.7 on 2023-12-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutocalendar', '0003_calendarauthtoken_calendarevent_calendaruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarauthtoken',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
