# Generated by Django 4.2.7 on 2023-12-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plutocalendar', '0004_calendarauthtoken_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='email',
            field=models.EmailField(default='placeholder@placeholder.com', max_length=254, unique=True),
        ),
    ]
